
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 7.3
 PARAMETER PROC_INSTANCE = psv_cortexa72_0
 PARAMETER stdin = psv_sbsauart_0
 PARAMETER stdout = psv_sbsauart_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexa72
 PARAMETER DRIVER_VER = 1.2
 PARAMETER HW_INSTANCE = psv_cortexa72_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = ddrpsv
 PARAMETER DRIVER_VER = 1.3
 PARAMETER HW_INSTANCE = axi_noc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scugic
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = psv_acpu_gic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_4
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_5
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_6
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = zdma
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_adma_7
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_apu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = canfd
 PARAMETER DRIVER_VER = 2.4
 PARAMETER HW_INSTANCE = psv_canfd_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = coresightps_dcc
 PARAMETER DRIVER_VER = 1.8
 PARAMETER HW_INSTANCE = psv_coresight_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pmonpsv
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_coresight_fpd_atm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_coresight_fpd_stm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pmonpsv
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_coresight_lpd_atm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_crf_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_crl_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_crp_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emacps
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = psv_ethernet_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emacps
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = psv_ethernet_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_afi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_afi_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_cci_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_gpv_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_maincci_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_slave_xmpu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_slcr_secure_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_smmu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_fpd_smmutcu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iicps
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = psv_i2c_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_4
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_5
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_6
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_pmc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_pmc_nobuf
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipipsu
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = psv_ipi_psm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_afi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_iou_secure_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_iou_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_slcr_secure_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_lpd_xppu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_ocm_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_ocm_ram_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_ocm_xmpu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_aes
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_bbram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = cframe
 PARAMETER DRIVER_VER = 1.2
 PARAMETER HW_INSTANCE = psv_pmc_cfi_cframe_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = cfupmc
 PARAMETER DRIVER_VER = 1.2
 PARAMETER HW_INSTANCE = psv_pmc_cfu_apb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = csudma
 PARAMETER DRIVER_VER = 1.7
 PARAMETER HW_INSTANCE = psv_pmc_dma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = csudma
 PARAMETER DRIVER_VER = 1.7
 PARAMETER HW_INSTANCE = psv_pmc_dma_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_efuse_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_global_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpiops
 PARAMETER DRIVER_VER = 3.8
 PARAMETER HW_INSTANCE = psv_pmc_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iicps
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = psv_pmc_i2c_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = psv_pmc_ppu1_mdm_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = qspipsu
 PARAMETER DRIVER_VER = 1.12
 PARAMETER HW_INSTANCE = psv_pmc_qspi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_qspi_ospi_flash_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_rsa
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = rtcpsu
 PARAMETER DRIVER_VER = 1.10
 PARAMETER HW_INSTANCE = psv_pmc_rtc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sdps
 PARAMETER DRIVER_VER = 3.10
 PARAMETER HW_INSTANCE = psv_pmc_sd_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_sha
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmonpsv
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = psv_pmc_sysmon_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_xmpu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_xppu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_pmc_xppu_npi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_psm_global_reg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_0_atcm_global
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_0_atcm_lockstep
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_0_btcm_global
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_0_btcm_lockstep
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_1_atcm_global
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_1_btcm_global
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_r5_tcm_ram_global
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scugic
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = psv_rcpu_gic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_rpu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartpsv
 PARAMETER DRIVER_VER = 1.3
 PARAMETER HW_INSTANCE = psv_sbsauart_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_scntr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_scntrs_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ttcps
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = psv_ttc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = psv_usb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = usbpsu
 PARAMETER DRIVER_VER = 1.8
 PARAMETER HW_INSTANCE = psv_usb_xhci_0
END


